services:
  countriesapi:
    container_name: countries-api
    image: torigon/countries-api:latest
    environment:
      - VIRTUAL_HOST: where-in-the-world.torigon.fr
      - LETSENCRYPT_HOST: where-in-the-world.torigon.fr
  
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost:/etc/nginx/vhost.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  
  letsencrypt-companion:
  container_name: letsencrypt-companion
  image: jrcs/letsencrypt-nginx-proxy-companion
  restart: unless-stopped
  volumes_from:
      - nginx
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/acme:/etc/acme.sh
  environment:
      DEFAULT_EMAIL: lenny.zanotelli24@gmail.com